### ISSUE TITLE
[CON-223] Cmd/Ctrl + Shift + Backspace doesn't stop streaming of diff

### ISSUE THREAD

**Issue by sestinj** [continuedev/continue#1012]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS:Mac
- Continue:0.9.91
- IDE:VS Code
```

### Description

When the diff view is briefly going away it is because I am using the cmd+shift+backspace shortcut to cancel the generation, but after a second it comes back because streaming was not successfully cancelled.

https://github.com/continuedev/continue/assets/33237525/8fd80572-8fe9-4330-a563-2d7d59239d94

[This](https://github.com/continuedev/continue/blob/221d020053ad36ca39dd156776dd711a6920f77f/extensions/vscode/src/diff/horizontal.ts#L273) is the function that gets called and is responsible for cancelling, so this is the starting point to debug.

### To reproduce

1. Highlight code
2. Type '/edit fix this' or something similar
3. when it starts generating, press cmd/ctrl+shift+backspace
4. it will briefly go away but streaming continues and the diff view will return

<sub>[CON-223](https://linear.app/continue/issue/CON-223/cmdctrl-shift-backspace-doesnt-stop-streaming-of-diff)</sub>

**Comment by justinmilner1** [comment]
Continuing discussion from Discord: 
I was concerned that _streamSlashCommand wasn't behaving correctly because the generating function ideStreamRequest wasn't yielding anything.  
After looking into it further, this seems to be the intention - ideStreamRequest and up is intended for streaming into the chat, not the diff. 
This is so parameters like 'recap' can be set to stream into the chat, without disrupting the diff.
