### ISSUE TITLE
Add requestOptions to OpenAI provider HTTP calls

### ISSUE THREAD

**Issue by 64q** [continuedev/continue#1046]
### Validations

- [x] I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [x] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

### Problem

Hi guys!

Thanks for your awesome tool! I'm currently using a custom vLLM endpoint with basic auth in front of it and I'm using the OpenAI provider.

It seems the `requestOptions` configuration is not injected in this provider (in fact, it's only used in the `LlamaCpp` provider). This prevents from injecting custom headers inside each request performed against the LLM endpoint in case you are using the OpenAI provider.

### Solution

Add the `requestOptions` in the OpenAI provider `fetch`es (or maybe make it even more generic in every provider?)

**Comment by sestinj** [comment]
@64q we do in fact use requestOptions for all LLM providers by injecting the same `fetch` to all of them (code [here](https://github.com/continuedev/continue/blob/2f67ded712f15f007acae7be2a42fa5738a74364/core/config/handler.ts#L99-L125) ).

I'm wondering if you're seeing this problem because you're trying to add an Authorization header? This will be overridden by the `apiKey` property, which translates into `"Authorization": "Bearer xxx"`. I believe LlamaCpp may just be the only one which *doesn't* use the `apiKey` property, which is why it seemed to work. More information here: https://continue.dev/docs/model-setup/configuration#authentication

**Comment by sestinj** [comment]
this does bring up a good point though that we probably ought to have the custom headers override apiKey, rather than the other way around!

**Comment by 64q** [comment]
> @64q we do in fact use requestOptions for all LLM providers by injecting the same `fetch` to all of them (code [here](https://github.com/continuedev/continue/blob/2f67ded712f15f007acae7be2a42fa5738a74364/core/config/handler.ts#L99-L125) ).
> 
> I'm wondering if you're seeing this problem because you're trying to add an Authorization header? This will be overridden by the `apiKey` property, which translates into `"Authorization": "Bearer xxx"`. I believe LlamaCpp may just be the only one which _doesn't_ use the `apiKey` property, which is why it seemed to work. More information here: https://continue.dev/docs/model-setup/configuration#authentication

You are completely right, I'm adding an `Authorization` header and the OpenAI provider seems to override the header with the `Bearer` one, even if I've a custom `Authorization` header already declared in my config file.

Thank you for your quick answer!

**Comment by 64q** [comment]
> this does bring up a good point though that we probably ought to have the custom headers override apiKey, rather than the other way around!

If you have any idea whether you will address this issue, please do not hesitate to let me know. 🤗

**Comment by sestinj** [comment]
@64q This has now been addressed in a recent commit! https://github.com/continuedev/continue/commit/e150f7d26fb076bcdfb1832013ecbff2b93b060d
