### ISSUE TITLE
Do not send tab autocomplete request when I make a new file?

### ISSUE THREAD

**Issue by therohitdas** [continuedev/continue#1085]
### Validations

- [X] I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

### Problem

When I open a new file, the following is appearing as tab autocomplete:
![Screenshot 2024-04-06 at 12 40 32 AM](https://github.com/continuedev/continue/assets/43847374/23e78f2f-1f50-4fd3-867c-6ba540e51717)
Full text:
I'm not sure I understand the context of your message. It appears you have provided a sequence of placeholders (fim\_prefix, fim\_suffix, fim\_middle) but no actual data to replace them with.

### Solution

Maybe do not send tab autocomplete request on new file or only send filename, copyBuffer as context for autocomplete?

I am using Groq for autocompletion.

**Comment by sestinj** [comment]
@therohitdas It looks like the problem is that Groq has no models trained for autocomplete. While it is of course the fastest API available and we'd love them to support a code model, none of mixtral, llama 70b, or gemini are trained on the dataset required for tab-autocomplete.

If you're looking for the fastest tab-autocomplete experience possible, I would recommend setting up starcoder2 7b with Fireworks AI: https://continue.dev/docs/walkthroughs/tab-autocomplete#setting-up-with-starcoder-2-7b-recommended
