### ISSUE TITLE
[CON-228] "url" context provider

### ISSUE THREAD

**Issue by sestinj** [continuedev/continue#1156]
### Validations

- [X] I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

### Problem

The docs context provider will crawl an entire site and find multiple pages, but oftentimes you only want literally one page

<sub>[CON-228](https://linear.app/continue/issue/CON-228/url-context-provider)</sub>

**Comment by oldluke92** [comment]
is the HTTP context provider what you are looking for ?
https://github.com/continuedev/continue/blob/main/core/context/providers/HttpContextProvider.ts

**Comment by justinmilner1** [comment]
@sestinj I think single-page-crawl should probably just be an option to set from within the AddDocsDialog? (rather than a whole new context provider)

I also see the case for a slider or input box to specify the max number of pages to crawl. Doesn't look like there is a max pages limit currently - I tried with a Wikipedia page and indeed that crawled indefinitely.

What do you think?

**Comment by sestinj** [comment]
@justinmilner1 I think this would be nice. Max depth seems like the right thing, otherwise it's hard to prioritize one page vs. the other when they are same depth.

Let's add this option to `SiteIndexingConfig` and then instead of doing the silly thing that I did and pass a freely defined object over the webviewProtocol for index/addDocs (https://github.com/continuedev/continue/blob/preview/core/protocol.ts#L65-L66), let's pass a `SiteIndexingConfig`. Probably just use the URL input by the user as both starting and root URL so the UI remains simple.
