### ISSUE TITLE
Allow other SCM setups for VSCode (remove git SCM requirement)

### ISSUE THREAD

**Issue by jonnyboynewton** [continuedev/continue#1209]
### Validations

- [ ] I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [ ] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

### Problem

The VSCode plugin doesn't function in a workspace that doesn't have git (so for a perforce client-based workspace, for example).
I get the following error:
![image](https://github.com/continuedev/continue/assets/47508472/834858ef-3235-4b52-b4f7-40a66ff0c080)

Why does it need the git SCM plugin?  What is it doing that it would need that?

### Solution

Allow the workspace to have other than the git SCM extension active.

**Comment by sestinj** [comment]
@jpaveg @jonnyboynewton I've removed this dependency in the latest pre-release, so this should be resolved. Let me know if for some reason you're still having problems.

We use git to manage indexing between branches, but this should still work fine in a perforce workspace. I added the dependency explicitly so that it could force the git extension to load prior to Continue, but it turned out that this had unintended side-effects/didn't work as I expected

**Comment by jonnyboynewton** [comment]
> @jpaveg @jonnyboynewton I've removed this dependency in the latest pre-release, so this should be resolved. Let me know if for some reason you're still having problems.

Excellent! Thanks!

> We use git to manage indexing between branches, but this should still work fine in a perforce workspace. I added the dependency explicitly so that it could force the git extension to load prior to Continue, but it turned out that this had unintended side-effects/didn't work as I expected

is this 0.9.123?  or do I need to wait for 124?

**Comment by jonnyboynewton** [comment]
nvm - i see 124 available now
