### ISSUE TITLE
requestOptions for custom headers is not working with v0.8.28

### ISSUE THREAD

**Issue by michaelgloeckner** [continuedev/continue#1301]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: Windows 10
- Continue: v0.8.28
- IDE: VSCode 1.89.1
```

### Description

Setting custom request header with "requestOptions" in config.json is not working anymore with v0.8.28

  "models": [
    {
      "title": "Mixtral@Ollama",
      "provider": "ollama",
      "model": "mixtral",
      "apiBase": "http://some_ollama_url/",
      "requestOptions": {
        "headers": {"Authorization": "Basic QVBJXYYYZZZZZYYYY="}
      }
    },

### To reproduce

1. setup model in config.json and use llm service like ollama which has basic authentication.
2. define "requestOptions" with Authorization header
3. check if continue.dev can connect to llm service
4. using v0.8.28 unauthorized error appears -> Error: HTTP 401 Unauthorized from http://some_ollama_url/api/chat
5. using v0.8.27 connection can be established

**Comment by sestinj** [comment]
@michaelgloeckner This happens because the `apiKey` property overrides your header. To use authorization you can follow here: https://docs.continue.dev/setup/configuration#authentication

But it does make sense that your custom headers should override apiKey, not the other way around, so I made a change here: https://github.com/continuedev/continue/commit/e150f7d26fb076bcdfb1832013ecbff2b93b060d
