### ISSUE TITLE
add a "request a compilete after idle/hotkey/..." mode

### ISSUE THREAD

**Issue by Dawn-Xu-helloworld** [continuedev/continue#1338]
### Validations

- [X] I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [ ] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

### Problem

For a no-GPU, self-host LLM, the previously compilete mode would make a lot of requests to server, but server can't deal with such a lot of requests.

### Solution

So I think if we add a "request a response after keyboard idle for some times" or "after a hotkey" or after something, in order to make less requests and cost less computing resources, for a self-host server

**Comment by sestinj** [comment]
@Dawn-Xu-helloworld There are a couple of options to achieve this that you can already do within Continue. The first is that you can set a trigger key for inline suggestions.

To do this, add the following to your VS Code settings:

```json
{
 "editor.inlineSuggest.enabled": false 
}
```

And add this to your keybindings settings file (you can choose any shortcut you'd like):

```json
{
    "key": "alt+\\",
    "command": "editor.action.inlineSuggest.trigger"
  }
  ```

The second option is to increase the debounceDelay in Continue's config.json so that it won't send a request on every keystroke: https://docs.continue.dev/walkthroughs/tab-autocomplete#tabautocompleteoptions
