### ISSUE TITLE
Improvement related to full screen chat window

### ISSUE THREAD

**Issue by dbsxdbsx** [continuedev/continue#1543]
### Validations

- [X] I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

### Problem

For the full-screen window:
![image](https://github.com/continuedev/continue/assets/17372655/e7aff0bc-1079-4c40-b9e7-971a15931eac)
1. whatever is input in the message box before sending, once the page is toggled out(ctrl+tab) to another one then toggle back, it loses all info---this is quite useful, because there is some code need to be pasted in the message box again and again for just one message sending.
2. the full-screen chat data would be lost once the whole vscode workspace is restarted.

### Solution

1. save the message held in the input box before sending;
2. retain the whole chat window with its message if the page tab is pinned---When restarting the workspace, users could continue to chat in the full window.

**Comment by devbyjonah** [comment]
@sestinj I opened a PR to fix this issue and a couple of other problems with fullscreen mode, but I wanted to get your thoughts on the webview panel 'retainContextWhenHidden' option. 

Enabling it resolves this issue and fixes sending highlighted code to the continue input when in fullscreen mode, but the docs warn that it can have a high memory overhead:
>retainContextWhenHidden has a high memory overhead and should only be used if your panel's context cannot be quickly saved and restored.

 I couldn't find any more information on this, but I assume that the memory costs would be similar to what is already being used with the sidebar view since it also retains context? LMK what you think, we can probably find another way to solve this, but switching between tabs will still be a lot slower since the view is essentially resetting every time without this.

**Comment by sestinj** [comment]
@devbyjonah thanks for bringing up the option—it's definitely okay to use it (we do in the main sidebar), and without it covering up the window would reset, which we definitely want to avoid. PR looked great and merging now!
