### ISSUE TITLE
When using Anthropic 3.5 Sonnet: Error generating autocompletion:  ValidationException: stop_sequences: each stop sequence must contain non-whitespace

### ISSUE THREAD

**Issue by virajkanwade** [continuedev/continue#1660]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS:
- Continue:
- IDE:
- Model: Bedrock: Claude 3.5 Sonnet
- config.json:
  
  "tabAutocompleteModel": {
    "title": "Bedrock: Claude 3.5 Sonnet",
    "provider": "bedrock",
    "model": "anthropic.claude-3-5-sonnet-20240620-v1:0",
    "region": "us-east-1"
  },
```

### Description

Autocomplete shows a warning popup when autocomplete is enabled and configured to use anthropic models.

Found a similar issue for a different application. https://github.com/BerriAI/litellm/issues/3286. They have fixed it https://github.com/BerriAI/litellm/pull/3436/files

**Comment by sestinj** [comment]
@virajkanwade I've solved this [here](https://github.com/continuedev/continue/commit/b8b8da842ef136235016014d9bea97f80f4243af), but if at all possible I would recommend avoiding using Anthropic for autocomplete, as it is more expensive, less accurate, and will have more formatting errors because it was not trained for the task. One great option is [codestral](https://docs.continue.dev/walkthroughs/set-up-codestral)

**Comment by virajkanwade** [comment]
Ohhk.

AWS Bedrock has Claude 3.5 sonnet but not codestral. Since i have already configured Claude was trying to use it for both. I guess will try to setup codestral on sagemaker.
Thanks
