### ISSUE TITLE
Paste (Cmd+V/context menu) does not work in sidebar in Pre-Relase 0.9.192

### ISSUE THREAD

**Issue by fry69** [continuedev/continue#1892]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: macOS
- Continue: 0.9.192
- IDE: VSCode
```

### Description

Pasting via Cmd+V and context menu does not work inside the sidebar in Pre-Release `0.9.192`, it works in stable `0.8.44`, see discussion in Discord starting here -> https://discord.com/channels/1108621136150929458/1108621136830398496/1268627074923630702

**Comment by Patrick-Erichsen** [comment]
Thanks for opening this up, I've seen similar reports in Discord. 

My hunch is that this change, which introduced the ability to copy/paste images, is the root cause: https://github.com/continuedev/continue/pull/1810/files#diff-9b165b7ad9a83be06c605622226adb53904539b6efcf7426bf116aad184f4419R263-R290

**Comment by Patrick-Erichsen** [comment]
@fry69 - this should fix it: https://github.com/continuedev/continue/pull/1899

**Comment by fry69** [comment]
Fixed in Pre-Release 0.9.193
