### ISSUE TITLE
Diff algorithm problem

### ISSUE THREAD

**Issue by YouJiacheng** [continuedev/continue#2039]
### Validations

- [X] I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [x] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

### Relevant environment info (Edited)
```
- OS: Windows
- Continue:
- IDE: VS Code
- Model:
- config.json:
```

### Problem
When using Ctrl+I, many selected lines don't change, but I still need to accept/reject these "null" changes.
But I must select all of them, because I need to change the first X lines and last Y lines.
Example:
![image](https://github.com/user-attachments/assets/f4c8f6b4-4acc-4a1a-99de-38085f9ea5fd)

### Solution

Support edit in diff format like https://aider.chat
![image](https://github.com/user-attachments/assets/c3e34828-cf4b-4cae-92ff-148bdff8f5b3)

Even if the model output is not in diff format, UI should only show the diff so that user only need to accept/reject changes.

Just like Cursor:
![image](https://github.com/user-attachments/assets/5d6ed3b8-8a95-4bf4-a21c-8cd479367e03)

**Comment by sestinj** [comment]
Thanks for sharing the clear example! This looks like a problem with our diffing algorithm, so your example will come in handy as a unit test that we can use to validate correct behavior. Will let you know if we have updates

**Comment by YouJiacheng** [comment]
Thanks!
Glad to hear that Continue already has a diff algorithm (unfortunately it doesn't work for me).

But beside the diff algorithm for UI, diff edit format can also be a great enhancement for faster and cheaper edit.

Zed just released an impressive demo of their newly introduced Fast Edit Mode:
 https://x.com/zeddotdev/status/1825967818329731104

**Comment by sestinj** [comment]
@YouJiacheng I'm working on this right now and have good new and bad news
Good: It seems to work fine for me
Bad: It seems to work fine for me

I'd really like to be able to reproduce this so we can have a high confidence fix, so I've been writing some tests. But once these passed, I tried to just reproduce in the product itself.

I tried the following:

a) paste this into a new file
```python
from fastapi import FastAPI

app = FastAPI()

@app.get("/")
def read_root():
    return {"Hello": "World"}

@app.get("/landing")
def read_landing_page():
    return {"message": "Welcome to the landing page"}
```

b) highlight the file, press cmd+I, and enter "Instead of returning the message, the landing page endpoint should 'raise HTTPException(status_code=404, detail="Page not found")'"

c) for me it gave the following output:

<img width="663" alt="Screenshot 2024-09-05 at 4 28 11 PM" src="https://github.com/user-attachments/assets/bf4fe2cf-b3f7-4fba-b063-2cf8eb8095c1">

I'm wondering if you could try this again in 0.9.207 and let me know if you still have the same problem, or even better, if you have other examples of bad outputs, these would be very useful as well.

Either way, I'll be working on trying to make the diff algorithm correct in every case possible

**Comment by YouJiacheng** [comment]
Oh, I should have mentioned that the OS is Windows!!!

**Comment by YouJiacheng** [comment]
Fixed by https://github.com/continuedev/continue/commit/2040f86899bf6c6cb7a8fcc6c758456b828656c2

It works fine in [0.8.51](https://github.com/continuedev/continue/releases/tag/v0.8.51-vscode)

![image](https://github.com/user-attachments/assets/f446b6c7-97a6-437e-81cf-16774ca64adc)

**Comment by YouJiacheng** [comment]
https://github.com/continuedev/continue/blob/2040f86899bf6c6cb7a8fcc6c758456b828656c2/core/util/verticalEdit.ts#L72-L85

Shouldn't we use `const splitLines = (str: string) => str.split(/\r?\n/);` instead of `.split("\n")` and `.trimEnd()`?

Just a style preference, haha.

BTW, the "When highlighted is empty" case is not very readable.
