### ISSUE TITLE
Consolidate continue files into one directory

### ISSUE THREAD

**Issue by joewinke** [continuedev/continue#3085]
### Validations

- [X] I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

### Problem

All continue files should be consolidated into ./.continue

Previously prompts were held in ./.prompts but now prompt files are in ./.continue/prompts for prompts v2
https://docs.continue.dev/customize/deep-dives/prompt-files

This is fine, however the .continuerules file needs to be in root
https://docs.continue.dev/customize/deep-dives/rules

Which is now spreading continue files throughout the project in an illogical scheme.

### Solution

I propose all continue files such as .prompts and .continuerules files exist in ./.continue

**Comment by sestinj** [comment]
@joewinke I appreciate the feedback on this

We believe that above all else it is necessary to make using .continueignore and .continuerules easy to use, and nesting them inside of a folder would harm that. Since these are probably where 90% of users stop, we're optimizing for that

While we could optionally allow them to exist in .continue, this optionality would create potential for confusion

Seeing as we're likely to revisit all of these files in the near future, which will force another pass on their organization, I'm going to close this issue for now
