### ISSUE TITLE
Extension stays at 'Loading Continue server...'. on Ubuntu 22.04, python 3.10.6

### ISSUE THREAD

**Issue by TyDunn** [continuedev/continue#309]
This issue was reported by two users:
- @simseb https://github.com/continuedev/continue/issues/300#issuecomment-1653050133
- @cyril-schroeder-ox https://github.com/continuedev/continue/issues/300#issuecomment-1653566728

**Comment by sdwr** [comment]
same for me, don't see any errors that looks related in the console.

**Comment by bhaktatejas922** [comment]
same issues on macos

**Comment by aston314** [comment]
Sever can not run on MacOS.

**Comment by sestinj** [comment]
@aston314 @bhaktatejas922 @sdwr An update for those watching this issue:

1. I'm working [here](https://github.com/continuedev/continue/issues/320) on a solution to bundle the python code as an executable, which I expect to solve this issue
2. For the time being, I've added documentation [here](https://github.com/continuedev/continue/tree/main/extension#troubleshooting) on how to troubleshoot this problem

Let me know if there are any updates on your end, and I'll send another message once packaging is ready!

**Comment by sestinj** [comment]
@aston314 @bhaktatejas922 @sdwr Closing this issue, as we have since
1. Packaged the server to a consistent binary
2. Heard from Ubuntu+windows+mac users that it has worked
3. Included testing as a part of CI on Ubuntu+mac+windows

If for some reason there is still an issue, feel free to reopen this issue or create a new one
