### ISSUE TITLE
Prompts overriden by weird generic ones

### ISSUE THREAD

**Issue by qb3l-pplsi** [continuedev/continue#313]
**Describe the bug**
Prompts reset to weird ones and don't complete. Here is an example just sending a prompt without any context of a file. The simplest example

**To Reproduce**
1. Install extension
2. Setup OpenAI key
3. Do any kind of prompt
4. Prompt will load for a little while and then get replaced by a new prompt (which never responds)

**Expected behavior**
Extension gives back an appropriate response

**Screenshots**
<img width="555" alt="Screenshot 2023-07-27 at 3 55 47 PM" src="https://github.com/continuedev/continue/assets/110841972/8cedec6a-4de9-40a9-a4d7-7155e64dc1d5">

Notice `how do you pass messages to iframes` gets turned into `can you help me with my math homework?`

**Environment**
- Operating System: MacOS
- Python Version: 3.10.11
- Continue Version: v0.0.211

**Console logs**
Don't see anything on `.continue/continue.logs` nor on VSCode extension logs that may give me a hint

**Additional context**
Where are these random prompts coming from?

**Comment by moghammed** [comment]
I have the same issue. These are my query logs:

    This is a log of the exact prompt/completion pairs sent/received from the LLM during this step
    
    ############################################
    
    Prompt: 
    
    <User>
    Code in this file is highlighted (<filename redacted>.ts):
    ```
    `CREATE RANGE INDEX node_idx IF NOT EXISTS FOR (n:Node) ON (n._id);`
    ```
    
    <Assistant>
    - Highlight code section and ask a question or give instructions
    - Use `cmd+m` (Mac) / `ctrl+m` (Windows) to open Continue
    - Use `/help` to ask questions about how to use Continue
    
    <User>
    what does this query do?
    
    
    
    ############################################
    
    Prompt: 
    
    <User>
    Write a short title for the following chat message:
    
    

I've also checked my OpenAI usage stats, and they have gone up. Only by $0.0003, so not an issue at all, but at least the prompt seems to be arriving on their end.

**Comment by sestinj** [comment]
Thanks for these details. There's definitely an error occurring during the first request (given we're not seeing a "completion" in the logs), leading to the confusion on the second. For reference, this is what success will look like: there is a summary of the response above the actual response, and in the issue here, we're only seeing the summary of the non-existent response:

<img width="466" alt="Screen Shot 2023-07-28 at 10 25 15 AM" src="https://github.com/continuedev/continue/assets/33237525/5973c5d5-663a-4ba9-8047-449d2edc35f3">

**Comment by sestinj** [comment]
@qb3l-pplsi @moghammed This behavior was caused by swallowing an error, and then trying to summarize an empty string (apparently math homework is the first thing gpt4 thinks of when unprompted 🤷‍♂, whereas gpt3 once told me "The quick brown fox jumped over the lazy dog. The lazy dog was not pleased." ). Continue will now display an error if it occurs, in which case I will be able to solve the problem basically immediately. Please let me know how it goes this time.

(there's also a chance that it just works this time, as I've squashed numerous bugs today)

**Comment by qb3l-pplsi** [comment]
I’ll give it a try over the weekend and report a new bug if necessary. I think if you’ve found the root cause we can close this one
