### ISSUE TITLE
Unable to activate, URI error

### ISSUE THREAD

**Issue by cwmoriarty** [continuedev/continue#316]
I have added an OpenAPI key and left the Server Url to the default of `http://localhost:65432`

it's unclear how this operates, are there installation steps to run a daemon or something?

Console Log:
```
console.ts:137 [Extension Host] Websocket import
console.ts:137 [Extension Host] Using Continue version:  0.0.212
console.ts:137 [Extension Host] Error activating extension:  TypeError: Cannot read properties of undefined (reading 'uri')
	at g3 (/Users/cwm/.vscode/extensions/continue.continue-0.0.212/out/extension.js:54:9214)
	at b3 (/Users/cwm/.vscode/extensions/continue.continue-0.0.212/out/extension.js:54:10548)
```

**Comment by sestinj** [comment]
Thanks for the report, I believe I know the issue and will push a change in the next 5 minutes. But also to be certain, you meant 65432, not 6543, right?

**Comment by sestinj** [comment]
I believe I know the error, and I'll push a fix in the next 5 minutes

**Comment by sestinj** [comment]
The new version is v0.0.213 and should not run into this issue.

No installation steps necessary, except for Windows users there is occasionally a required shell command to run, but you would be notified of this requirement. There is a server that runs in the background though, which you could choose to run on your own rather than it being automatically started by the extension (hence the Server URL)

**Comment by cwmoriarty** [comment]
Looks fixed. 

Seeing `Starting Continue Server... (it may take a minute to download Python packages)`
