### ISSUE TITLE
[Feature request] Make all text navigation keys functional

### ISSUE THREAD

**Issue by selfagency** [continuedev/continue#364]
**Is your feature request related to a problem? Please describe.**
Up/down and home/end keys don't work when editing prompts. You can only edit your prompt by clicking within the text or navigating with the left/right keys.

**Describe the solution you'd like**
Make all text navigation keys functional.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by sestinj** [comment]
@selfagency I see the problem here. Since we want to use up/down to navigate history + the dropdown, this is overriding the navigation within the textarea. Right now, we check whether there are any newlines in the textarea, but this check doesn't catch the case where the window is thin and text wraps around to the next line without a line break. I'll check what HTML properties can be exploited here to make a proper fix.

**Comment by sestinj** [comment]
@selfagency This is now fixed, you'll be able to use up/down arrows for their intended purposes. Pushing the newest version later tonight with a handful of other fixes
