### ISSUE TITLE
[Feature request] Don't require colons (`:`) after slash (`/`) commands

### ISSUE THREAD

**Issue by selfagency** [continuedev/continue#365]
**Is your feature request related to a problem? Please describe.**
The need to add a colon after a slash command is a needless annoyance. The extension should be able to distinguish between a slash command and not a slash command without it.

**Describe the solution you'd like**
Drop the colon.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by sestinj** [comment]
@selfagency Continue can identify slash commands without the colon, so the functionality is there, but the problem seems that the way we display this in the dropdown menu is misleading. I'm going to remove the colons there. Curious if there was anywhere else that led to thinking colons were required so I can clear this up.

**Comment by sestinj** [comment]
@selfagency Colons have been removed, so I'm going to close this. If you have other ideas about how to make this more clear, feel free to add a comment and reopen!
