### ISSUE TITLE
Azure OpenAI API Keys don't seem to be working

### ISSUE THREAD

**Issue by vladiliescu** [continuedev/continue#373]
**Describe the bug**
Azure OpenAI API Keys are not recognized.

**To Reproduce**
1. Configure Continue to connect to Azure OpenAI as below

```python
   models=Models(
        default=OpenAI(api_key="--", model="gpt-4", server_info=OpenAIServerInfo(
            api_base="https://---.openai.azure.com",
            engine="--",
            api_version="2023-03-15-preview",
            api_type="azure"
        ))
    ),
```

2. Try to chat with it
3. Error: `openai.error.AuthenticationError: Incorrect API key provided: XXX`.

Happens with both the primary and secondary keys, I can only assume it's not connecting to the proper endpoint.

Setting the `continue.OPENAI_API_KEY` setting in VSCode as low-key suggested by the docs didn't improve things.

**Expected behavior**
I'm able to chat with the model :). 

**Environment**
- Operating System: MacOS Ventura
- Python Version: 3.11.4
- Continue Version: v0.0.305

**Comment by sestinj** [comment]
@vladiliescu It turns out this was a mistake in our documentation, and the kwarg names should be `openai_server_info` instead of `server_info`. I've tried with the exact setup, saw that it failed, then made that change, and it worked. Updating documentation now. And giving a look to your other issue next!

**Comment by vladiliescu** [comment]
Thanks @sestinj, I can confirm that it works!
