### ISSUE TITLE
Flexible continue configuration with external python (aka frozen packages fix)

### ISSUE THREAD

**Issue by bra1nDump** [continuedev/continue#386]
# Problem(s)
- [Main] Currently python and all dependencies are distributed using pyinstaller and @sestinj mentioned the 'frozen' package terminology not allowing for importing external modules in config or their custom steps.
- Users don't have intelisence when editing their custom continue config
- Startup is slow. I think we should be able to speed it up because we woudn't need to load all executable into memory like we do with pyinstaller
- Users can't debug their scripts using breakpoints

# Solution
Solves the main problem, but lays ground work for others.

Setup a full python environment in `.continue`

1. Have a prerequisite a user has python installed - for instance vscode native python extension assumes you have it in your path already.
2. Install poetry with all the packages in .continue folder. I have played around with using `execa`, a cross platform child process library
3. Distribute python server sources with the extension, or similarly upload to s3
4. Install the continue core dependencies within the .venv within .continue
5. Allow additional file to source user dependencies from (will also be in .continue somewhere).
6. Finally allow users to add their own python files somewhere in .continue that can use any of the core or user dependencies. 
7. Bonus - setup a .vscode in .continue with the goodies to allow users get intelisence + debugging of their custom scripts

**Comment by sestinj** [comment]
Some background: before we were doing something very similar:
- Create python venv (not with poetry because that requires an additional installation, more surface area for things to go wrong)
- Install dependencies from a .whl file
- Activate the venv
- Run the python file from the venv

Issues with this:
- Dependency resolution is SUPER slow, especially on Windows. It sometimes took >5 minutes to download the packages. To me this means that we would absolutely have to package them together is S3, or maybe there is some other way around this
- Much more surface area for mistakes. Since moving toward pyinstaller, we've basically eradicated all startup issues. With enough testing, maybe I could be confident in another approach, but it was quite bad before and I want to avoid this
- Requires python to be installed. Surprisingly often python isn't installed on someone's computer

Upsides we are attempting to gain:
- Intellisense in the config file (note that in the worst case, one way to achieve this is by downloading the source code to a folder that doesn't do anything except provide reference for the interpreter)
- Faster startup (potentially). There are two versions of this: 1) upon initial download, downloading dependencies locally was slower, but 2) after subsequent updates, we get to cache the dependencies instead of downloading and starting
- Allow outside deps!

**Comment by bra1nDump** [comment]
1. Resolution. You are right, we shouldn't run resolution on the clients at all. Could potentially be overcome by using something like setuptools to bundle all dependencies in a 'fat' wheel and download that.
2. Indeed the setup will be harder to get right.
3. Python distribution. I tried looking for a cross platform python bash one liner installer and failed. A hack that might work:
  - Create a simple bootstrap.py with code to create a virtual environment with its own python interpreter (venv is available from within python as far as I understand) 
  - Package it with pyinstaller so we can simply run the binary on the user's device
  - Now that we have .venv we can download our fat wheel from step 1 and run_continue_server.py
  
I think its worth mentioning I have never distributed a python program this way. It might be a smart idea to try to get someone with experience. They would figure it out x5 most likely. For example one of the contributors from either of packaging tools pyinstaller, cx_Freeze or setuptools to help with this on a contract basis. There is also a company that specializes in this, maybe they can offer a contract or pitch their own solution https://www.activestate.com/company/contact-us/

**Comment by sestinj** [comment]
I like the fat wheel idea. Main drawback is that you must have Python installed, but there's no reason we can't just "if python installed then download pyinstaller binary instead". Thoughts on this? It seems probably true that the intersection of users that a) don't have python installed and b) want to use custom imports in the config file, is probably small.

Setup will be harder, but this just means making sure testing gives enough confidence., and some of this is already setup.

**Comment by bra1nDump** [comment]
My idea is still only use the system python for bootstrapping the venv that will have its own python installation with the version we want.

You are right that the dual setup would work for 99% of the users.
For own sanity I would still suggest trying the bootstrapping venv with pyinstaller. I want to give it a try sometime within the next couple of days. Very curious if this hack would actually work. That's the closest I will ever get to a OS boot loader hacker

**Comment by bra1nDump** [comment]
Yet another promise of a cross platform python runtime PyOxy
An internet friend pointed me to this thing: https://gregoryszorc.com/docs/pyoxidizer/main/pyoxy.html which looks promising

**Comment by sestinj** [comment]
@bra1nDump Finally...we have a solution for this : ) Using typescript with esbuild, theoretically any package can be bundled!

**Comment by bra1nDump** [comment]
That's awesome! I heard santa really endorses projects using a single runtime this year. Wait ... maybe they have to be deer powered
