### ISSUE TITLE
Stale files in @file-name context provider (have been since changed / deleted)

### ISSUE THREAD

**Issue by bra1nDump** [continuedev/continue#391]
We need to watch the directory for changes and update the context on changes. The freshness of the files is key for usefulness of continue so this is high priority.

**Comment by sestinj** [comment]
Seems easy enough to do: use vscode api to listen for file saves/creations/deletions, pass to server, then update meilisearch through context provider

Another way to solve file freshness is to just grab the contents of the file at prompt compilation time (assuming contents don't strongly affect search ranking, not a strong assumption) instead of storing in meilisearch, but that doesn't address new files.

**Comment by sestinj** [comment]
@bra1nDump Did this in #396, figured I'd share before merging
