### ISSUE TITLE
LocalAI support

### ISSUE THREAD

**Issue by mudler** [continuedev/continue#411]
**Is your feature request related to a problem? Please describe.**
I've just tried continue with LocalAI (https://localai.io), it's awesome! Continue is a great project and LocalAI is a good fit to run with as a service behind.

**Describe the solution you'd like**
We have just merged an example on how to use Continue with LocalAI: https://github.com/go-skynet/LocalAI/pull/940, would be great to have the example also on the continue website, or provide a direct integration maybe?

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by sestinj** [comment]
This would be great! We can make a new subclass of `LLM` within Continue that supports LocalAI, then it will be as easy as toggling a dropdown to use LocalAI (after it's otherwise set up). Any interest in tackling this? Happy to show you where to start, or even write the whole thing. It isn't so big a task, mostly just writing the small amount of code necessary to call the APIs

**Comment by gregoryca** [comment]
Do note, usually localai runs at port 8080. It would be handy to be able to change the target port and URL.

I can expose my localai for example to the internet, behind traefik.
If i expose it to the internet, i only need to point to a url instead of a telnet address so it would be awsome if we immediately could specify the URL.

**Comment by sestinj** [comment]
This can already be done, though perhaps the docs are a bit hidden: https://continue.dev/docs/customization#azure-openai-service:~:text=Note%20that%20you%20can%20also%20use%20OpenAIServerInfo%20for%20uses%20other%20than%20Azure%2C%20such%20as%20self%2Dhosting%20a%20model

**Comment by gregoryca** [comment]
This indeed should work ! thanks voor your quick answer !

**Comment by sestinj** [comment]
@mudler Did a bit of cleaning to the docs and we now link here to LocalAI: https://continue.dev/docs/customization#local-models-with-openai-compatible-server

Also joined your Discord server - makes sense to keep our communities in touch : )

I'll give this issue a day or two before closing - let me know if any other thoughts on how we could integrate Continue more closely with LocalAI, these 2 projects are a great fit!

**Comment by mudler** [comment]
Apologize in my delay in answering, but I was vacationing last week and had limited connectivity. Just joined the discord as well! 

That's super - I'll make sure we link and add a section as well for Continue directly in our docs pointing to the examples!

**Comment by sestinj** [comment]
Cool, no worries! Keep in touch : )
