### ISSUE TITLE
Command + M (Minimize window) is overwritten by Continue on Mac

### ISSUE THREAD

**Issue by thomasaarholt** [continuedev/continue#422]
**Describe the bug**
Command + M is a system-wide hotkey to minimize the window of the current application (ie. the VSCode editor window). With the Continue extension installed, Command + M opens the extension's window within the editor instead.

I think it would be preferable for Continue to use a different hotkey, at least on mac.

**Comment by sestinj** [comment]
I've been considering this as well, want to make a decisive and final decision at some point. Other possibilities are command k and command l, both ergonomic and not overly commonly used. Any other thoughts? If you were to (or already have) change the key binding what would you change it to?

**Comment by thomasaarholt** [comment]
Command + K is the "shortcut for more shortcuts" (aka "chords"). Look at the status bar when you press Command + K). Command + I triggers autocomplete in Python for me - I actually didn't know about this shortcut.

Two suggestions:
- Control + M, which doesn't seem used (and would mean - I assume - Continue has the same shortcut across OSes)
- Command + K, Command + M, which would then use the [VSCode chords](https://code.visualstudio.com/docs/getstarted/keybindings#_keyboard-rules).

**Comment by muendelezaji** [comment]
Not sure if this warrants a separate issue, but on the more general subject of keyboard shortcuts, the extension also seems to override some VSCode system shortcuts that I feel are pretty commonly used:
- ⇧+⌘+L - Select All Occurrences of Find Match / Search Editor: Select All Matches
- ⇧+⌘+M - View: Toggle Problems
- ⇧+⌘+Enter - Insert Line Above
- ⇧+⌘+R - Go to Symbol in Workspace / Search Editor: Search Again

For context, none of the other 80+ extensions I have installed overrides these shortcuts, so it would be nice if Continue didn't either. For now I've had to disable them to keep the system setting, but ideally that could be solved by using less general/less common hotkeys, using chords as suggested above, or maybe even scoping the shortcuts to when the Continue panel is active.

**Comment by sestinj** [comment]
Continue is now using cmd+shift+L, cmd+L, and cmd+I. It won't be possible for us to select a shortcut that is both convenient and never used for other purposes, since there are so few keys to choose from, but we choose a convenient shortcut with the understanding that folks who are frequently using less common shortcuts are more likely to know how to change the keybindings for Continue. A note has also been added to our tutorial to make it clear that this is possible.

I'm going to close this issue as it's title doesn't make it the best candidate for discourse around keyboard shortcut choices (now that our defaults are cmd+L), but if this continues to be a concern please feel free to keep the conversation going elsewhere!
