### ISSUE TITLE
How to bring continue back?

### ISSUE THREAD

**Issue by BenedictKing** [continuedev/continue#426]
**Describe the bug**
My continue server always no response since some days ago.
I have tried all the ways in https://continue.dev/docs/troubleshooting but none of them could working.

**Environment**
- Operating System: MacOS 10.15.7
- Python Version: 3.11.4
- Continue Version: v0.0.350
- Remote develop on remote server with SSH

**Console logs**
Nothing appears in log file `continue.log`. It is empty!

**Comment by BenedictKing** [comment]
My current fallback solution is to install Continue v0.0.329 which give me a suggestion to install continue extension on remote server. Now I could ask continue as always.

**Comment by sestinj** [comment]
Sorry to hear this! To be sure, you were seeing something like this and the arrow just never disappeared? We did in fact make some changes that were intended to fix SSH right around version v0.0.329, so I'll look into what might have changed there. Is there anything else I should know about the setup so I can test on my own mac?


<img width="357" alt="Screen Shot 2023-08-29 at 5 58 11 PM" src="https://github.com/continuedev/continue/assets/33237525/46ab66b9-5c34-495d-9f3a-d25f6110b751">

**Comment by BenedictKing** [comment]
![截屏2023-08-30 上午11 29 59](https://github.com/continuedev/continue/assets/2107330/4e46ac94-3d60-479c-aa79-385b54b11d29)
I just upgrade to latest v0.0.352 but still got same problem as my screenshot. I tried `lsof -i :65432 | grep "(LISTEN)" | awk '{print $2}` on remote server and my local computer, the continue server is only running on remote server.

**Comment by sestinj** [comment]
I think the solution is probably to have Continue downloaded only on the local computer—this is actually the new intention since that version—should have realized this earlier.

This also has the benefit that you can use the same instance of Continue across local+remote workspaces

**Comment by BenedictKing** [comment]
I don't know. For me, running continue only on remote server is good. As I don't have to care about VPN or proxy to access OpenAI API.

**Comment by sestinj** [comment]
Hadn't considered this, sorry. It makes sense.

It's possible the issue is that the React app is local and the server is remote. If so, port forwarding would be the solution here and I could try something like this:

```typescript
// If running on remote, forward the port
if (
  vscode.env.remoteName &&
  vscode.extensions.getExtension("continue.continue")?.extensionKind ===
    vscode.ExtensionKind.Workspace
) {
  await vscode.env.asExternalUri(vscode.Uri.parse(getContinueServerUrl()));
}
```

and then you would theoretically be able to just run the extension in remote only.

Can you test forwarding the port manually and see if this works? If so, I'll move forward with that.

But also interesting is that I've tested with my own SSH server, and am currently in a state where the server is running on the SSH server, but not locally, and things are working. I've tried both with the extension installed ONLY remote and on BOTH remote and local, like below. This makes me wonder whether a fresh start would be helpful.

<img width="318" alt="Screen Shot 2023-08-30 at 12 50 58 AM" src="https://github.com/continuedev/continue/assets/33237525/ff498aa3-e5a4-4535-be2d-4fd133a0ab62">

**Comment by BenedictKing** [comment]
Yeah, port forwarding 65432 is working. Now I have two continue server running. But the local one may not connected to the openai service and output logs.

**Comment by BenedictKing** [comment]
Maybe there is one problem, I have two remote server but I could only forward one 65432 port to local. So only one remote server is actually providing continue service....

**Comment by sestinj** [comment]
One idea is to allow the servers to run on different ports so they can both be forwarded. This seems like a reasonable option that should exist anyway to avoid port conflicts.

Do you feel this would be a good solution for you?

**Comment by BenedictKing** [comment]
I found out that I can set different "continue:server url" settings for different workspace. This problem is soloved.

**Comment by sestinj** [comment]
Good point, forgot you can just map to different ports when forwarding. Glad it's all working now!
