### ISSUE TITLE
continue runs too slowly

### ISSUE THREAD

**Issue by xjy198903** [continuedev/continue#466]
The plug-in runs too slowly, much slower than the original 0.0.329, and after entering the question, nothing is displayed until a long time later (maybe more than a minute, or even longer), along with the response. Currently, the default MaybeProxyOpenAI-gpt4 is used, which means it has not been touched since installation.

**Environment**

- Operating System: ubuntu 22.04
- Python Version: 3.10.12
- Continue Version: 0.0382

**Comment by xjy198903** [comment]
Yes. #463 has been resoled by updating continue to the latest.
and how to configure an API key for gpt3.5 or&nbsp; gpt4?

---Original---
From: "Nate ***@***.***&gt;
Date: Wed, Sep 13, 2023 01:23 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [continuedev/continue] continue runs too slowly (Issue #466)




 
@xjy198903 This is potentially because of geographic location. We are only serving the free usage server from the US—is it possible that this is the cause? One solution might be to use your own OpenAI key
 
Also, does this mean that your previous problem here (#463) has been resolved?
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving tis because you were mentioned.Message ID: ***@***.***&gt;

**Comment by sestinj** [comment]
To configure an API Key you can:
1. Get an API key from https://platform.openai.com
2. In Continue, type '/config' to open the file `~/.continue/config.py`
3. Paste the API key from step (1) into the `api_key` field in MaybeProxyOpenAI.

There are full instructions [here](https://continue.dev/docs/reference/Models/maybe_proxy_openai)

**Comment by xjy198903** [comment]
I have configured the api-key inside config.py as shown below:
![image](https://github.com/continuedev/continue/assets/29084288/d2aa9e57-efac-4dd0-b84e-14ac2c800da9)

After restarting vscode, I get this error:
![image](https://github.com/continuedev/continue/assets/29084288/72a2a2ff-5c51-45cd-bf33-2996d618ae70)
I'm sure the api-key is available.

**Comment by sestinj** [comment]
Can you make sure the API key is set for both models (default _and_ medium)?

If the issue persists after doing this, my guess would be that there is some VPN / firewall / etc. blocking access to OpenAI

**Comment by xjy198903** [comment]
> Can you make sure the API key is set for both models (default _and_ medium)?

yes. and The problem remains.I'm going to give it up

**Comment by TyDunn** [comment]
> I'm going to give it up

@xjy198903 Can we hop on a call to debug this? We can't let you give up :)

**Comment by sestinj** [comment]
@xjy198903 I'm very sorry that this turned out to be such a frustrating experience - I realize that it is an entire month later, but we've been working on making this experience better. I believe that your problem can be solved by using the OpenAI class, where your config.py would look like this:

```python
...
config=ContinueConfig(
  ...
  models=Models(
    default=OpenAI(api_key="<API_KEY>", model="gpt-4"),
    summarize=OpenAI(api_key="<API_KEY>", model="gpt-3.5-turbo")
  )
)
```

But we've also seriously upgraded our UI so that you can do all of this without having to touch the config. If you click the "+" button in the bottom left corner of the screen, you can select the OpenAI option at the top, enter your API key, select a model, and you should be completely good to go.

If you do want to use the config file, we've also made sure that you now get intellisense, so you don't have to guess at which properties or imports exist. I hope you're willing to take another look at Continue and that we can help you out - please let us know if there's anything else we can do!

**Comment by sestinj** [comment]
Many months later: we've upgraded Continue so that it no longer uses the confusing Python server, which was the likely cause of many problems here. I'd love if you had the chance to give it another try and share feedback. Since I haven't heard back in a while, I'm going to close the issue, but please don't hesitate to re-open or start a new thread!
