### ISSUE TITLE
Quick fix with continue doesn't include the selected code

### ISSUE THREAD

**Issue by wizche** [continuedev/continue#473]
**Describe the bug**
When selecting a piece of code and asking for Quick fix with Continue will generate the following wrong prompt:
```
undefined

How do I fix this problem in the above code?: undefined
```

**To Reproduce**

1. Go to a file with some code
2. Highlight a function
3. CTRL-SHIFT+P and select Quick fix with Continue
4. See the wrong prompt

**Environment**

- Operating System: Debian 11
- Python Version: 3.9.2
- Continue Version: 0.0.383

**Screenshots**

Here a screenshot showing that the highlighted code is actually detected correctly (`test.go 16-25`) but is not properly injected into the prompt.

![2023-09-13-214621](https://github.com/continuedev/continue/assets/1062939/cd4b30f2-9d03-4e1c-b04c-b7c729ab56ce)

**Comment by sestinj** [comment]
The Quick Fix with Continue command is actually intended for use with the VS Code "quick fix" feature where you can get suggestions on how to fix underlined red/yellow code. Here's an example:

<img width="591" alt="Screen Shot 2023-09-13 at 1 23 05 PM" src="https://github.com/continuedev/continue/assets/33237525/8e0ce4e3-154f-4768-90e9-f8a9e0a254c2">

And then selecting "Ask Continue" would put the surrounding lines and the error into the prompt.

I'll check if I can keep the "Quick Fix with Continue" command out of the command palette, since it is not intended to be used there.

**Comment by wizche** [comment]
Ahhh, I see... Yeah having the entry in the command palette is a bit misleading... Why not keeping it and having it the purpose I was intending too? When you select a piece of code you can `Fix/Improve that code` that trigger a request with a specialized prompt for that. I like that I can just select code and ask for actions. Similarly also the `/comment` would be cool to be accessible via Command Palette.

**Comment by sestinj** [comment]
Releasing a version today that will stop "Continue Quick Fix" from showing up in the command palette, so I'm going to close this issue. 

I like the other idea - it's out of the scope of this issue, but something we'll definitely consider. If you still feel yourself strongly wanting this feature, you can ping us in Discord or make another issue and we'll give it a +1 priority-wise : )
