### ISSUE TITLE
How to run in IntelliJ IDEA

### ISSUE THREAD

**Issue by star7810** [continuedev/continue#482]
I noticed that the documentation for the "continue" site has added support for IntelliJ IDEA, but the link seems to be incorrect. How do I use it in IDEA? I don't seem to find the corresponding plugin.

```
https://continue.dev/docs/how-continue-works


- "You can install it from the JetBrains Marketplace [here](https://continue.dev/)."-
```

**Comment by sestinj** [comment]
@star7810 we probably shouldn't have added the link so soon, since the plugin is still under review by JetBrains, but I believe it will be ready in no more than a few days. I'll share when it's ready!

If you'd like to try manually downloading, you may or may not be able to do so [here](https://plugins.jetbrains.com/plugin/22707-continue-extension/versions/stable/398000). Note: absolutely no guarantees if you do this

**Comment by sestinj** [comment]
@star7810 Update: Here is a significantly improved pre-release: https://discord.com/channels/1108621136150929458/1108621136830398496/1159049720799449119

We'll be adding the real version to the store in the upcoming days, and I'll share again when that happens

**Comment by sestinj** [comment]
@star7810 there is now an improved version in the JetBrains store: 0.0.8. We're working toward an official release soon, and would love to hear your feedback!

**Comment by sestinj** [comment]
The JetBrains Plugin is now in version 0.0.25+ and has been stable for about a month, so I think it is safe to close this issue. Please let me know if you have any troubles in setting it up!
