### ISSUE TITLE
feature request:  Add a new option to disable summaries

### ISSUE THREAD

**Issue by Aincvy** [continuedev/continue#489]
**Is your feature request related to a problem? Please describe.**
 After a summary fails, such as due to network issues, the original answer disappears.

**Additional context**
After disabling the summary, the first N characters of the user input/answer can be used as the summary. Other reasons include that I feel I don't need a summary at all and it can save money, although not much.

**Comment by sestinj** [comment]
We've just added this feature a couple of days ago : )

https://continue.dev/docs/reference/config#:~:text=if%20set%20to%20%60true%60%2C%20continue%20will%20not%20generate%20summaries%20for%20each%20step.%20this%20can%20be%20useful%20if%20you%20want%20to%20save%20on%20compute.

Just set disable_summaries=True in the config file. It's also a goal to make all settings available in UI so that this is more discoverable

We are also not in the middle of redesigning things so that summaries are less prominent

**Comment by sestinj** [comment]
fixing this in just a minute... I'll let you know when the new version is ready

**Comment by sestinj** [comment]
This is ready in the newest PyPI package version: https://pypi.org/project/continuedev/

**Comment by sestinj** [comment]
closing this issue, since it looks like everything is resolved—ofc let me know if not
