### ISSUE TITLE
Unable to download `run` and `melisearch`

### ISSUE THREAD

**Issue by gatspy** [continuedev/continue#493]
I haven't been running since installing vscode.
it's either unable to download `run` or unable to download `meilisearch`.
There's no need for something so difficult to use!

![image](https://github.com/continuedev/continue/assets/804446/370a496b-9e69-4d74-a05b-f9f9955f6396)
![image](https://github.com/continuedev/continue/assets/804446/5b6f8068-e716-4b7b-b8ca-83ef903dbe18)

**Comment by shiqimei** [comment]
> @gatspy It's likely that there is something (e.g. firewall) blocking the download. If you'd like to use Continue, the best option would be using the PyPI package, like here: https://continue.dev/docs/walkthroughs/manually-run-continue#recommended-use-the-continuedev-pypi-package
> 
> Let me know what else I can do to help

I don't think relying on users' local machine environment to setup extension is a good idea and ask users to install dependencies from PyPI is not a good user experience too.

**Comment by gatspy** [comment]
I also tried to manually download `Meilisearch` and place it in ~/.continue/server, but when I started Continue from VSCode, it deleted the files.

**Comment by TyDunn** [comment]
@gatspy I'm sorry this has been such a frustrating experience for you. The VS Code extension is a beta product that launched seven weeks ago, created and maintained by two people. Since then, we have squashed hundreds of bugs for folks, who let us know they are having a problem and gave us the necessary context to figure it out for them. Slowly but surely, it has gotten much better, but it looks like you have found a situation that we have not perfected yet. Thank you for letting us know about it.

If you show us respect and help us help you, we will do the same and get this sorted for you  👍

We are going to need more information:
1. Are you behind a firewall?
2. What happened when you tried to [using the PyPI package](https://continue.dev/docs/walkthroughs/manually-run-continue#recommended-use-the-continuedev-pypi-package)?
3. How did you try manually downloading Meilisearch?
4. Operating System: [e.g. MacOS]
5. Python Version: [e.g. 3.10.6]
6. Did you figure anything else out while [troubleshooting](https://continue.dev/docs/troubleshooting)?

We can hop on a call or chat about this on [Discord](https://discord.gg/vapESyrFmJ) if you would like too :)

**Comment by TyDunn** [comment]
> I don't think relying on users' local machine environment to setup extension is a good idea and ask users to install dependencies from PyPI is not a good user experience too.

@shiqimei We [rely on the local machine environment](https://continue.dev/docs/how-continue-works), so that we can easily [support more IDEs](https://github.com/continuedev/continue/pull/457), enable folks to set up Continue for their entire team with one server, and set Continue up for [a future where LLMs are much more capable](https://continue.dev/docs/walkthroughs/headless-mode). This is a long term bet that unfortunately results in many frustrating but solvable challenges in the near term. In just a few weeks, things have already got much more reliable and the number of issues is already slowing.

You are right that installing dependencies from PyPI is not a good user experience. This suggestion is intended to help folks move forward while waiting for us as we also triage and prioritize dozens of bugs from other users daily too. There are also known scenarios that we have yet to find a better solution for yet: (a) a firewall, VPN, or other issue is stopping Continue from automatically downloading the server binary, (b) you are on an OS where the binary fails to run (e.g. RHEL8), (c) you are using an air-gapped computer, and (d) you want to self-host Continue. If you have ideas about how to make these user experiences better, we'd love for you to contribute!

**Comment by sestinj** [comment]
@gatspy and @shiqimei, I wanted to update you both that we've taken great measures to try and improve this experience:
- The Continue VS Code extension now comes pre-installed with the server, so it doesn't have to be downloaded after-the-fact, and users should never have to run the server manually unless they want
- We've increased the reliability of the Meilisearch setup, and ensured that even if it were to fail, none of the other functionality of Continue is affected
- We've added options to the PyPI continuedev package to give better control over Meilisearch in case you wanted to setup manually and disable or run Meilisearch on your own

And as a testament to the reasons that we decided to build a separate server, we have also released a JetBrains extension that is available for alpha testing on their marketplace: https://plugins.jetbrains.com/plugin/22707-continue

I appreciate the feedback from both of you, especially gatspy for being willing to go through some debugging on your own. We're working hard to make Continue as seamless as possible, and hope that you'd be willing to give it another try. If not, we completely understand, but will always be open to hearing about what we can do better. Hopefully this issue is resolved and can be closed if everything works smoothly, but if not let me know!

**Comment by sestinj** [comment]
Excited to share an even further development with the Continue server: it is no longer necessary. This means that the extension is entirely self-contained, no need to build or download meilisearch or the binary. Going to close this issue, but thank you again for giving your feedback : )
