### ISSUE TITLE
continue displays empty results when using ollama v0.0.20

### ISSUE THREAD

**Issue by cheuk-cheng** [continuedev/continue#499]
**Describe the bug**
continue displays blank results when using ollama v0.0.20

**To Reproduce**

1. Launch Ollama app
2. Enter the following code in Visual Studio Code
```
names = ['red', 'green', 'blue']

def print_names(names):
    for index in range(len(names)+1):
        print(names[index])

print_names(names)
```
3. Highlight the entire program
4. Ask "Are there any bugs in this Python code?" and hit enter key.
4. Nothing is returned except the title of the query is updated to match the question

**Environment**

- Operating System: MacOS
- Python Version: 3.10.11
- Continue Version: v0.0.394

**Logs**
No log is displayed after clicking the magnifier glass icon

**Comment by sestinj** [comment]
@cheuk-cheng Looks like there was a breaking change in version 20. Looking through the change log to see what happened—I'll try to have an update by tomorrow morning

**Comment by jmorganca** [comment]
Hi @cheuk-cheng, @sestinj and other folks who may have encountered this: sorry you hit this issue! It's fixed in [v0.0.21](https://github.com/jmorganca/ollama/releases/tag/v0.0.21), which was just released and can also be downloaded from [ollama.ai](https://ollama.ai/).

Feel free to tag me here or shoot me a note if you encounter any more issues with Ollama + Continue!

**Comment by cheuk-cheng** [comment]
Thanks @sestinj and @jmorganca for the quick fix.  Ollama v0.0.21 is working fine now.
Have a nice weekend!

**Comment by sestinj** [comment]
Great! Appreciate the quick report before this could affect too many others. Have a great weekend!

And thx again @jmorganca
