### ISSUE TITLE
 JetBrains plugins cannot be used in an offline environment

### ISSUE THREAD

**Issue by TTMRonald** [continuedev/continue#540]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [ ] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: windows 10
- Continue: jetbrains 0.0.7
- IDE: pycharm professional 2023.1.4
```

### Description

Please tell me how to configure and use the 'Continue' plugin in PyCharm in an offline environment.

After successfully configuring and using the 'Continue' plugin in my offline environment for VS Code, I wanted to follow the configuration steps for PyCharm according to the VS Code setup. However, I encountered some issues after installing the plugin.

1. When trying to manually start the service and clicking 'Manually start server,' a blank pop-up window appears.

2. After offline installation of 'continuedev' using pip, the '~/.continue' directory still contains only an empty folder named 'server'.

**Comment by sestinj** [comment]
@TTMRonald The steps that should allow this to work are:
1. `python -m continuedev` to start the server
2. In the PyCharm settings for Continue, set Server URL to "http://localhost:65432" and check the box for "Manually Running Server".
3. Click "Apply" 
4. Close and reopen the window

When you say a blank pop-up window appears, could you share what this looks like?

**Comment by TTMRonald** [comment]
@sestinj The screenshot of the blank window looks like this. This situation occurred when I clicked the manually start service button marked in the image.
<img width="936" alt="20231010103323" src="https://github.com/continuedev/continue/assets/18680409/2eb13597-4f0d-4d5b-8f11-95709d3d0172">

Furthermore, I executed this command, but it still didn't generate files like 'config.py', only a log file named 'continue.log' appeared.

**Comment by sestinj** [comment]
@TTMRonald The window opening is a bug, since it was doing something VS Code specific - I'll fix this and have it in the next released version.

Out of curiosity, how long did you wait for the Continue sever to start on its own before trying something else? There's some small chance that the download is taking a while, though I will also verify this original problem by testing myself.

For the python -m continuedev problem, there is a quick solution that should get you up and running. If you open the PyCharm settings > Tools > Continue, and check the box that says "Manually Running Server", then close and re-open the window, it should be able to connect and create the necessary folders. If for some reason this doesn't work, then there should almost certainly be some output from the python -m continuedev command with an error

**Comment by TTMRonald** [comment]
@sestinj Waiting for the window to open for 1-2 minutes resulted in an error prompt, which may have been caused by issues related to offline environment downloads. 

Following your instructions, I configured the manual start service path and was pleased to see that the necessary files were generated. 

I will continue to attempt to connect it to the remote environment where I have deployed the service. 

Thank you very much!

**Comment by sestinj** [comment]
@TTMRonald Glad this worked out! When you say remote service, are you serving the Continue server remotely?

Also, the error prompt - was this something inside of the Continue side bar? Would be good to know what happened, since I think there's a chance that this means the server actually did just take a while to download

**Comment by TTMRonald** [comment]
@sestinj I have set up a model service on a remote GPU server and I'm using Continue on another computer without a CPU. 

The error message did not appear in the Continue sidebar; it was an error prompt from the Continue plugin in PyCharm.

**Comment by sestinj** [comment]
Ok, thanks. If you ever see it again, please send my way.

And let me know if there's anything I can do to help with connecting the model.


If you're interested in getting a much improved version of the extension before it reaches the JetBrains store, you can install this from disk (or if you wait it should be released within a matter of days):
[continue-intellij-extension-0.0.8.zip](https://github.com/continuedev/continue/files/12852683/continue-intellij-extension-0.0.8.zip)

**Comment by TTMRonald** [comment]
@sestinj Great, I'm excited to get an early taste of the new version of Continue. 

Additionally, I wanted to ask, if I want to recompile a JetBrains plugin so that I don't have to manually start the service in an offline environment, how should I go about it?

**Comment by sestinj** [comment]
do you mean recompiling so that the plugin starts the Continue server automatically, but by using `python -m continuedev` instead of downloading the binary?

**Comment by TTMRonald** [comment]
@sestinj Yes, it would be great if we could import the plugin and have Continue work seamlessly in an offline environment without the need to manually run 'python -m continuedev'. 

For example, adding a feature on the plugin page to configure an offline environment's pip source address would allow us to configure it, and after a restart of the IDEs, it would automatically download and start the service.

**Comment by sestinj** [comment]
@TTMRonald This is a great idea - you wouldn't want it to automatically download the pip package would you? Or are pip downloads allow-listed in the environment?

**Comment by TTMRonald** [comment]
@sestinj It might be even better if it could automatically download the pip package based on the configured source address.

**Comment by sestinj** [comment]
Do you have some kind of company repository of pip packages? Just curious to know how this works - it would help me figure out the best solution

**Comment by laurentperez** [comment]
this is also because the 0.0.7 version attempts to download the continueserver binary, then Meilisearch, and it takes some time, timeouts may happen

the plugin UI should use a progress bar or a spinner to wait for the readiness of the underlying backend. I can't PR it but, you get the idea

I'll test the 0.0.8 version ;)

**Comment by sestinj** [comment]
@laurentperez this is definitely what we should do, appreciate the input! We have a spinner, but it doesn't display immediately. I think a progress bar would be much more helpful

Let me know how 0.0.8 goes!

**Comment by TTMRonald** [comment]
@sestinj Yes, in an offline environment, the source address only needs to be specified during `pip install` to take effect, for example `pip install continuedev -i repository_url_of_pip_package --trusted-host=repository_ip_address`.

**Comment by TTMRonald** [comment]
Resolved.
