### ISSUE TITLE
Support code auto complete

### ISSUE THREAD

**Issue by conbein49** [continuedev/continue#563]
### Validations

- [X] I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

### Problem

Hi there,

I am using Continue with codellama running in local, and it runs pretty good. Thanks for the work.

Is there a plan to support code auto complete(e.g. I write a comment for what to do, and it gives the suggested code directory in the editor) like Copilot?

**Comment by sestinj** [comment]
Hi @conbein49. We don't plan to support tab auto-complete too soon, but we would like to eventually. I'm going to link here to another issue and close this one if that's alright, just so that we can track everything in one place. https://github.com/continuedev/continue/issues/440

If you're interested in local tab autocomplete, there are a few interesting tools you could try, such as https://github.com/danielgross/localpilot, Tabby, and Fauxpilot

**Comment by conbein49** [comment]
> Hi @conbein49. We don't plan to support tab auto-complete too soon, but we would like to eventually. I'm going to link here to another issue and close this one if that's alright, just so that we can track everything in one place. #440
> 
> If you're interested in local tab autocomplete, there are a few interesting tools you could try, such as https://github.com/danielgross/localpilot, Tabby, and Fauxpilot

Thx for the reply and the suggestion.
I would try localpilot. :-)
