### ISSUE TITLE
Improve Telemetry Opt-Out Experience: In-Extension Setting (not ~/.continue/config.py)

### ISSUE THREAD

**Issue by Nezteb** [continuedev/continue#567]
### Validations

- [X] I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

### Problem

Opt-out telemetry is already meh, but the docs explain how to opt out of telemetry by modifying `~/.continue/config.py`, which is odd to me: https://continue.dev/docs/telemetry

This is not typically the way editor extensions handle telemetry configuration. Usually it's managed in the editor settings:
<img width="1177" alt="screenshot_2023-10-19_at_16 24 33@2x" src="https://github.com/continuedev/continue/assets/3588798/db76c0c7-a235-4abe-bb02-2baeec5bfd07">

Continue does not offer that:
<img width="1208" alt="screenshot_2023-10-19_at_16 21 54@2x" src="https://github.com/continuedev/continue/assets/3588798/0b95b9fc-2562-4f57-9eb7-683a8339c4ed">

### Similar issues

I found a few similar issues related to opting out of telemetry, but none of them suggest an extension setting:

- https://github.com/continuedev/continue/issues/47
- https://github.com/continuedev/continue/issues/60

### Solution

I want a way to easily disable telemetry from the editor extension settings.

**Comment by nukeop** [comment]
Likely by design

**Comment by sestinj** [comment]
@Nezteb @nukeop This is more than a fair ask. It isn't any goal of ours to make opting out difficult. I believe the design of this simply came from our viewing config.py as the focal point around which all Continue config happens. If there's a built-in VS Code method that everyone expects, then we should adhere!

I'll make it happen in the next pre-release version, which should make its way to main within the following days after that. I'll update here soon as it's ready : )

**Comment by RobotCaleb** [comment]
Ideally these things are opt-in as otherwise often telemetry is already sent before I get the chance to opt-out.

**Comment by sestinj** [comment]
@Nezteb @nukeop This is now available in the latest pre-release, which I'm planning to merge to the main extension tomorrow. It a checkbox specific to the Continue setting, and it will modify the value in the config.py, which is always source of truth. Let me know how it works for you

**Comment by sestinj** [comment]
@RobotCaleb I understand where you're coming from here. We're careful not to send off miscellaneous info before any concrete action is taken, which means that if you come in as someone who knows they always like turning off telemetry, then updating the setting at the start will make sure nothing leaves your computer.

Even that which we do send is anonymous, cleaned thoroughly of PII, and largely consists of either generic numbers like "how many tokens were generated?" or categorical data like "which slash command was used?" or "which model is being used?"

The reason we are unlikely to make this opt-in is that an understanding of these basic interactions is critical to improving the product for our users. As an example, if our tutorial is doing no good, and nobody ever uses the /edit slash command because they aren't aware of it, it's important that we understand this in aggregate, so we know to spend time improving that area of the product.

**Comment by sestinj** [comment]
This fix is now available in the main release of the extension, and I haven't heard back in a couple of days, so going to close this issue.

But if there is anything else that doesn't seem right, if this doesn't work smoothly, or if it still feels too obscured, please do not hesitate to re-open!
