### ISSUE TITLE
Don't index binary (and other don't desired) files when using the codebase retrieval

### ISSUE THREAD

**Issue by kabachuha** [continuedev/continue#603]
### Validations

- [X] I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

### Problem

The embeddings codebase answering is very enjoyable, thank you! The problem is that during both the preparation and the retrieval processes it also takes into account binary files, which are both large and full of nonsense, such as pictures and sound files, significantly worsening the codebase question answering

### Solution

The best thing to do would be to add an easily editable property to the codebase formation config which will filter out the matching filename parts when indexing

**Comment by sestinj** [comment]
@kabachuha This is very important yes! We have default list of filetypes that we ignore—what are the ones here so I could add them?

But more importantly, we allow use of a `.continueignore` which uses the same syntax as .gitignore so that you can specify which files shouldn't be included in indexing. I still have work to do on having changes auto-update after indexing has already occurred, so I'll keep this issue updated as I fix that

**Comment by sestinj** [comment]
Auto-indexing is now complete, so I'm going to close this issue. If you end up seeing this some time later and could share what the type of binary file extension was, I'd still love to know so I can add it to our list of off-limits file types
