### ISSUE TITLE
Phind Codelamma prompt templates are not used properly (among other param issues)

### ISSUE THREAD

**Issue by dflatline** [continuedev/continue#616]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: MacOS 14
- Continue: 0.5.2
- Ollama: 0.1.8
```

### Description

The ollama phind model is not properly hooked up, leading to terrible output from the leading local code generation model.

There are several problems here:
 - The template messages are wrong (they are set to `llama2_template_messages` instead of `phind_template_messages`
 - The context length is wrong (phind-codellama is 16k context, not 2k)
 - The max_tokens field is wedged at 600; should be 8k
 - The name of the model is not how ollama actually names it[](url)

### To reproduce

1. Because I'm on a mac, I have plenty of vram for phind-codellama:34b-v2-q6_K, so I did ollama pull phind-codellama:34b-v2-q6_K. Note that with ollama and phind-codelamma, you must actually specify a full tag, especially if you want v2 and quantization.
2. Select Ollama Phind CodeLamma in Continue.dev.
3. Try to talk to it. Because the prompt templates are wrong, it will give you nonsense answers, often echoing the (incorrect) INST tags from llamma2 prompt template
4. Inspect the request to see that the model is using the wrong template

### Log output

```Shell
I managed to config the context_length in config.py, but I can't seem to find a way to fix either the prompt template, or the max_tokens parameter.

If you inspect the prompt, you get:

This is the exact prompt sent to the LLM: 

Settings:
context_length: 16000
model: phind-codellama:34b-v2-q6_K
max_tokens: 600

############################################

[INST] hi [/INST]
```

Note that these INST tags are not right. The prompt format is totally different: https://huggingface.co/Phind/Phind-CodeLlama-34B-v2

I did find a function that looks like it has this template (`phind_template_messages()` in server/continuedev/libs/llm/prompts/chat.py), but I can't find a way to hook it up via config.py.

I have a super-ugly patch to get everything working, which I will attach just for reference.
```

**Comment by dflatline** [comment]
This patch hacks things to work, but obviously you don't want to merge this:
[phind.patch](https://github.com/continuedev/continue/files/13323166/phind.patch)

I am new to the codebase, so I am not sure the best way to fix all of these issues cleanly :/

Maybe they can actually be fixed from config.py, but I tried for a couple hours and could not get it to override max_tokens correctly, let alone the prompt template. That's why the patch just changes the default for max_tokens... It was the only way I could get it to not be 600.

Oh, also you *do* have to edit config.py to name the model correctly. `phind-codelamma` is not enough. I had to do:

```
 default=Ollama(
                        title="Phind CodeLlama",
                        model="phind-codellama:34b-v2-q6_K",
                        context_length=16000
                ),
```

**Comment by sestinj** [comment]
@dflatline 

a) This setup is way harder than it should be and we've decided to make this the sole topic of next week, so this whole experience will improve.

b) I'm fixing the template message right now to point to the correct one. context_length I'm going to wait on as we design a better experience because I want to be careful about cranking that up to 16_000 for users who might not have such powerful hardware. But will address this is one way or another

To hook up `phind_template_messages` you can do this in config.py:

```python
from continuedev.libs.llm.prompts.chat import phind_template_messages
...

 default=Ollama(
     title="Phind CodeLlama",
     model="phind-codellama:34b-v2-q6_K",
     context_length=16000,
     template_messages=phind_template_messages
 ),
```

**Comment by dflatline** [comment]
Nice! I am glad to hear this is being worked on. To continue's credit, it is the only project I have found so far that even had some kind of support for different model prompt templates, other than ollama itself. Every project seems to be a nightmare to use with any other than a single specific model (and for open source models, the best-in-class seems to change weekly...)

What about the max_tokens problem? I could not seem to set that from either the Ollama model param arguments there, or where temperature was set, in config.py. Neither location had any effect.

**Comment by mantukin** [comment]
> What about the max_tokens problem?

I am also looking for an option to change the max_tokens value. I set it in the config file, but the extension ignores it. I am tired of receiving incomplete messages from the LLM. 600 is too small.

`This is the exact prompt sent to the LLM: 

Settings:
context_length: 16384
model: wizardcoder:13b-python
temperature: 0.01
max_tokens: 600

############################################`

**Comment by sestinj** [comment]
@dflatline @mantukin There was a bug causing override not to work. I've just fixed this and it will be ready in pre-release version 0.7.4 within the next 20 minutes. In the pre-release we now use a .json config file format, and you can set "max_tokens" in one of two ways:

```json
{
  "models": [
    {
      "title": "GPT-4",
      "provider": "openai-free-trial",
      "model": "gpt-4",
      "api_key": "",
      "context_length": 8192,
      "completion_options": {
        "max_tokens": 1002
      }
    }
  ],
  "completion_options": {
    "max_tokens": 1001
  },
...
}
```

Here, the model-specific completion_option (1002) will take precedence over the base completion_options (1001).

I've also changed the default value so that it increases along with the context length of the model. Will be half of the model's context length, capped at 2048.

**Comment by mantukin** [comment]
@sestinj Thank you for fixing it and explaining. Now everything works as it should.

Additionally, I think it would be more convenient for the user if `max_tokens` and `context_length` values were options in the settings window, along with the temperature slider.

**Comment by sestinj** [comment]
nice! and absolutely yes, I can make this happen.

**Comment by sestinj** [comment]
going to close this issue since main problem was addressed.

As for sliders in the UI settings, I think we are going to keep the options in .json. Reason for this is mainly an attempt to curb complexity and I think we can do a good enough job for most users that even thinking about context length or max tokens shouldn't necessary. The UI would get pretty cluttered / confusing for new users when there's a different max_tokens + context_length for each model
