### ISSUE TITLE
Release not work

### ISSUE THREAD

**Issue by vanarok** [continuedev/continue#639]
### Before submitting your bug report

- [ ] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: Ubuntu 22.04
- Continue: v0.6.4
- IDE Gitpod Web IDE
```

### Description

```
[2023-11-21 06:46:57] [WARNING] Failed to load config from /home/gitpod/.continue/config.py: module 'config' has no attribute 'config'
[2023-11-21 06:46:57] [WARNING] Failed to load config modifier from /home/gitpod/.continue/config.py: [Errno 2] No such file or directory: '/home/gitpod/.continue/config.py'
[2023-11-21 06:46:57] [DEBUG] ------ Begin Logs ------
[2023-11-21 06:46:57] [DEBUG] Downloading MeiliSearch with curl...
[2023-11-21 06:46:59] [DEBUG] Starting MeiliSearch...
[2023-11-21 06:46:59] [INFO] Meilisearch started at http://localhost:7700
[2023-11-21 06:47:00] [WARNING] Failed to load config modifier from /home/gitpod/.continue/config.py: [Errno 2] No such file or directory: '/home/gitpod/.continue/config.py'
```

### To reproduce

1. Run workspace 
3. Install continue 
4. Reload Web IDE 
4. Continue server fails to start, error in logs

**Comment by vanarok** [comment]
![Screenshot_2023-11-21-12-57-34-038_com kiwibrowser browser-edit](https://github.com/continuedev/continue/assets/6105977/a06ca90c-f113-4ecb-af58-bef2f583b33f)

**Comment by sestinj** [comment]
@vanarok Had Continue been working before and it was only this release that caused it to fail?

<img width="470" alt="Screen Shot 2023-11-20 at 10 59 14 PM" src="https://github.com/continuedev/continue/assets/33237525/04f4c7bc-b766-4689-81c4-ed5810a9a3a9">

And when you say failing to start, is this what you are seeing?

**Comment by vanarok** [comment]
> @vanarok Had Continue been working before and it was only this release that caused it to fail?
> 
> <img alt="Screen Shot 2023-11-20 at 10 59 14 PM" width="470" src="https://user-images.githubusercontent.com/33237525/284489293-04f4c7bc-b766-4689-81c4-ed5810a9a3a9.png">
> And when you say failing to start, is this what you are seeing?

Used to work. Yeah, I can see that.

**Comment by sestinj** [comment]
Ok, can you try creating an empty ~/.continue/config.py? I will also fix the bug, but this should be a temporary solution

**Comment by nicoboss** [comment]
I'm experiencing the exact same issue. The only version that works for me is `v0.0.412`.

To recreate this issue just try to install the latest release or latest pre-release on the `lscr.io/linuxserver/code-server:latest` Visual Studio Code Server docker image.

This extension is awesome. It's very unfortunate that I'm stuck on such an old version.

**Comment by sestinj** [comment]
@nicoboss @vanarok We've just released a version in pre-release for VS Code, v0.7.32, that no longer depends on the server, which means that this error should be impossible.

While in pre-release I can't guarantee there won't be one or two rough edges, but let me know if there are and I'll be cleaning them up the rest of this week before moving it to the main version

**Comment by nicoboss** [comment]
> @nicoboss @vanarok We've just released a version in pre-release for VS Code, v0.7.32, that no longer depends on the server, which means that this error should be impossible.
> 
> While in pre-release I can't guarantee there won't be one or two rough edges, but let me know if there are and I'll be cleaning them up the rest of this week before moving it to the main version

I tried out the latest PreRelease. It unfortunately doesn't work on code-server using the default settings as it makes my web browser trying to connect to `localhost:65433` which would be on my local machine and not the machine running code-server. Code-server offers a tunnel `https://65433.code-server.nico.re/` but I don't really understand how to change the config.json to use that instead of `localhost:65433`.

A screenshot showing the errors I got:
![ContinuePreReleaseCodeServerError](https://github.com/continuedev/continue/assets/623410/50f4031e-be24-4b6d-84a6-0240206a6479)

The currently running tunnels clearly show that the continue integrated server is running:
![ContinuePreReleaseCodeServerTunnels](https://github.com/continuedev/continue/assets/623410/4138a1ea-b399-4ca9-b6bf-af9fa33f06a1)

**Comment by nicoboss** [comment]
I just looked at the source code. `localhost:65433` seems to be hardcoded inside `gui/assets/index.js` so it seems impossible to change that using the config file. At least `localhost:65432` can be changed as it gets its value from `vscode4.workspace.getConfiguration("continue").get("serverUrl")` if specified.

**Comment by nicoboss** [comment]
I exposed port 65433 in the code-server docker and changed `http://localhost:65433` to `http://srp.nico.re:65433` in `~/.vscode-server/extensions/continue.continue-0.7.36-linux-x64/gui/assets/index.js` but unfortunately this results in the following CORS error:
![grafik](https://github.com/continuedev/continue/assets/623410/d69d7cec-bde8-4d5b-9e94-3eb14f550758)

**Comment by nicoboss** [comment]
I was able to fix the CORS issue by performing the following about:config changes:
```
dom.security.https_only_mode false
dom.security.https_only_mode_ever_enabled false
```

Now I'm stuck with Firefox complaining due to mixed content as code-server uses HTTPS while the server running on 65433 uses HTTP. I tried setting `security.mixed_content.block_active_content false` but doing so had no effect:
![grafik](https://github.com/continuedev/continue/assets/623410/eb2fb0a0-19f7-461f-b208-fa3a14412d5a)

**Comment by nicoboss** [comment]
I just got it working! One just has to use the tunneled port URL instead of forwarding the port and using a direct URL. In my case this was `https://65433.srp.nico.re:8443`. The reason this works is because the proxy server makes everything HTTPS and so there are no longer any issues with mixed content.
![grafik](https://github.com/continuedev/continue/assets/623410/721d81c7-a37e-42f9-b67e-93ce8fff0943)

![grafik](https://github.com/continuedev/continue/assets/623410/5bab56ca-e67e-4821-a780-1633ef8906af)

Can you please make this configurable so I don't have to edit the hardcoded `http://localhost:65433` in `~/.vscode-server/extensions/continue.continue-0.7.36-linux-x64/gui/assets/index.js` after every extension update?

**Comment by sestinj** [comment]
@nicoboss I added this in version 0.7.48. It's called "Proxy Server Url" in VS Code settings. Ideally I'll also be able to  get this programmatically but just hoped it would quickly solve your problem

**Comment by sestinj** [comment]
Going to officially close this issue: we are now using the built-in webview communication channel so that none of this setup is required
