### ISSUE TITLE
Problems with mouse selection

### ISSUE THREAD

**Issue by gpakoh** [continuedev/continue#652]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [ ] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [ ] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: Windows 10 x64 21H2
- Continue: v0.6.8
- Python 3.12.0
- VS-Code 1.84.2
```

### Description

After a recent update, the mouse stopped highlighting correctly. I filmed the problem. The video is attached
https://github.com/continuedev/continue/assets/140178096/d529ae2b-62b9-4cd6-b503-988fb8babbcc

**Comment by gpakoh** [comment]
Recently

> Спасибо за подробное видео! Вы наверняка помните, работало ли это в предыдущей версии до обновления или это началось недавно?

Recently

**Comment by sestinj** [comment]
@gpakoh I think I see the problem. The light gray message that says "^M to select code, ^ shift M to edit" is on exactly the line where the highlighting stops, which makes me think that is causing it. If you hover over the message like in this picture and then click "here", it will stop showing the message. Can you confirm that this solves it?

If so, I will move the message so that it can't get in the way

<img width="903" alt="Screen Shot 2023-12-15 at 3 50 29 PM" src="https://github.com/continuedev/continue/assets/33237525/70f234f4-198b-4953-ac96-03342e2da368">

**Comment by sestinj** [comment]
Going to close this issue, as we've moved the message, and made it more prominent so that it can clearly be seen to exist. Please feel free to re-open or create another issue if you feel this isn't properly solved
