### ISSUE TITLE
deepseek-coder:1.3b-base-q4_1 + ollama does not give any text

### ISSUE THREAD

**Issue by BananaAcid** [continuedev/continue#694]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: MacOS 14.1.2
- Continue: 0.7.54
- IDE: VSCode 1.85.0
- Ollama: 0.1.16
```

### Description

The context is not used, sometimes there is no result at all. Using Ollama from the commandline with this model or "Llama Coder", it works

### To reproduce

<img width="413" alt="Bildschirmfoto 2023-12-18 um 12 01 49" src="https://github.com/continuedev/continue/assets/1894723/00016713-d03c-40c1-b12e-0b303ef0435e">

**Comment by sestinj** [comment]
@BananaAcid I'm not 100% certain this is the only problem here, but I would say the first thing to try is use an instruct version of the deepseek model. Since the "base" models aren't trained on conversation, they will have a lot of difficulty responding to anything you say in a useful way, as is shown in this screenshot. They are mainly useful for tab-autocomplete

The instruct equivalent of what you have here would be [`ollama run deepseek-coder:1.3b-instruct-q4_1`](https://ollama.ai/library/deepseek-coder:1.3b-instruct-q4_1)

**Comment by BananaAcid** [comment]
Thank you, I will try that :)
