### ISSUE TITLE
Optimization suggestions in Jetbrains tools

### ISSUE THREAD

**Issue by Houtx** [continuedev/continue#720]
### Validations

- [ ] I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [ ] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

### Problem

1.The support for the Light theme is not good, and the icons are displayed incorrectly.      
![image](https://github.com/continuedev/continue/assets/17922172/d8545669-8dec-4d8e-80fd-53631e6229fb)

2.The display of the context style is problematic.
![image](https://github.com/continuedev/continue/assets/17922172/13610966-30fe-4034-b4a7-15dfeb199907)

3.When searching for files using the @Files command, it currently matches the file names in sequential order. I would like to suggest modifying it to match file names that contain the specified keywords.

For example, if we have a file named "Test.java", when searching with the command "@Files ts", it should be able to find all files that contain the letter "t" followed by any character and then the letter "s" (similar to the file search feature in JetBrains IntelliJ IDEA). 

4.Enhance the intelligent awareness of the current file context in the editor, making it more elegant, similar to GitHub Copilot Chat.

5.Improve the visual appearance of the UI, making it more appealing, similar to GitHub Copilot Chat or other AI assistants.

**Comment by sestinj** [comment]
@Houtx Thanks for this feedback! I'll have the theme problems fixed by the next version, and can make the file search a bit "fuzzier".

For 4., are you hoping that Continue will by default have the open file included as context?

For 5., are there any particular things that you like about Copilot Chat or others that you could share?

**Comment by Houtx** [comment]
> @Houtx Thanks for this feedback! I'll have the theme problems fixed by the next version, and can make the file search a bit "fuzzier".
> 
> For 4., are you hoping that Continue will by default have the open file included as context?
> 
> For 5., are there any particular things that you like about Copilot Chat or others that you could share?

For 4. I hope by default have the open file included as context.

For 5.  When I click copilot chat the plus sign in the lower left corner, a list of currently opened tab files will be displayed for me to choose from.
![image](https://github.com/continuedev/continue/assets/17922172/fc635ed2-924c-46e3-93d0-c98cfe5eff38)

**Comment by sestinj** [comment]
The icon and editor color have been fixed in 0.0.27, and I've made the file search a bit fuzzier so that it will match inexact filenames.

I think for 4 I will make it an optional part of the system message. This way it will be up to each user whether they want this behavior.

We have a feature that is basically the same as this: if you click "+ Add Context" in the bottom right of the input box, it will open the dropdown where you can select context providers. You've given me a good idea though that the first items listed in the file dropdown should always be the currently open files, so I'll make this change for the next version.
