### ISSUE TITLE
Ctrl+M minimizes the windows in Windows 11 = impossible to select code

### ISSUE THREAD

**Issue by leolivier** [continuedev/continue#782]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS:windows 11
- Continue:0.9.32
- IDE: vscode 1.85.2 
- Ollama 0.1.22
```

### Description

In Windows 11, the standard behavior of the Ctrl-M key is to send the window back. So, it is impossible for me to select code for Continue. 

### To reproduce

1. install continue in vscode on a windows 11 machine
2. open a file containing code and select some lines of code
3. see the tip saying "^M to select code, ^shift L to edit 
4. hit Ctrl-M and see the window go behind other windows  and not select the code
5. ask continue to explain the code selected w/ the mouse only and see it answering on some code you've never seen

**Comment by leolivier** [comment]
Well, after some other trials, I realized that the right key is Ctrl-Shift-M which works so the bug is on the tip itself

**Comment by sestinj** [comment]
@leolivier thanks for sharing this. ctrl-M actually is supposed to do something in Continue as well (selects code and restarts the session). It might be that the only reason we've gone so long without seeing tons of issues opened such as this is that its common for people to use full-screen mode.

Regardless, we're planning on switching up the keyboard shortcuts soon so that there won't be silly conflicts like this one. I'll keep the issue open until we've made the change!

**Comment by sestinj** [comment]
@leolivier Continue now uses ctrl-L instead of ctrl-M
