### ISSUE TITLE
Prompt output is sometimes empty until VSCode is restarted

### ISSUE THREAD

**Issue by NinjaPerson24119** [continuedev/continue#824]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [ ] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [ ] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: Ubuntu 22.04
- Continue: Ollama v0.1.23
- IDE: VSCode 1.86.0
```

### Description

The box where the output is supposed to be doesn't render until I restart the window. This occurs randomly. Sometimes it's fine.

### To reproduce

Run the LLM. Often only happens after a few runs.

![image](https://github.com/continuedev/continue/assets/32471098/6a392929-c226-4bb1-a82c-aaf6c753d4be)
Reloading the window fixes it.

**Comment by sestinj** [comment]
@NinjaPerson24119 Last weekend we started using Shiki to render code blocks because it gave syntax highlighting that matches the VS Code theme, but unfortunately it's been causing a handful of bugs like this. Sometimes doesn't render at all, oftentimes renders slowly, and after there are enough code blocks on the screen (e.g. try "write bubble sort in 20 different languages") they fail to be highlighted.

So yesterday I started figuring out how to get syntax highlighting in Monaco: https://github.com/continuedev/continue/commits/nate/monaco-not-shiki/

Almost done with this and may release today or tomorrow. Seems to avoid all of these problems

**Comment by m-e-conroy** [comment]
I'm experiencing the same issue, after a few queries it stops formatting the response and then eventually stops outputting responses altogether.  Using Continue as a connector to LMStudio.

**Comment by sestinj** [comment]
@m-e-conroy @NinjaPerson24119 @uninstallit this is now solved in the latest pre-release (0.9.52).

will close this issue as soon as I get any confirmation that it's working for you

**Comment by m-e-conroy** [comment]
@sestinj Working for me now.  Thanks!

**Comment by sestinj** [comment]
nice! closing, but if others don't see the same feel free to re-open
