### ISSUE TITLE
Allow "modifyConfig" to be async

### ISSUE THREAD

**Issue by Ryloxx** [continuedev/continue#826]
### Validations

- [X] I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

### Problem

My use case is that I want to be able to perform asynchronous tasks inside the [`modifyConfig`](https://github.com/continuedev/continue/blob/09a2f88bfc86194561f97d9cd7a08d1c8baa6580/docs/docs/model-setup/configuration.md?plain=1#L83) like dynamically fetch models metadata from the server.

### Solution

Putting "await"  [here](https://github.com/continuedev/continue/blob/09a2f88bfc86194561f97d9cd7a08d1c8baa6580/gui/src/hooks/useSetup.ts#L35) and [here](https://github.com/continuedev/continue/blob/09a2f88bfc86194561f97d9cd7a08d1c8baa6580/extensions/vscode/src/ideProtocol.ts#L499) will do the trick I think.
I have been doing that on my local installation and so far I got no problem.
A documentation update will be needed too.

**Comment by sestinj** [comment]
@Ryloxx It sounds like the goal here is to fetch the list of models from the server. We are currently working on building this feature into Continue by default and I haven't heard many other use cases for async modifyConfig, so I think the best thing to do is just finish building this feature.

I want to avoid async modifyConfig because allowing arbitrarily long-running functions would halt basically the entire extension from running until they are finished and I don't want to leave room for this to happen

**Comment by sestinj** [comment]
@Ryloxx we now allow you set set "model": "AUTODETECT" in config.json. Does this satisfy your use case?

**Comment by Ryloxx** [comment]
Yes, I got it working with "AUTODETECT". Thank you.
