### ISSUE TITLE
Unresponsive chat when using remote self-hosted Ollama server 

### ISSUE THREAD

**Issue by MattyRad** [continuedev/continue#946]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: PopOS 22.04
- Continue: 0.8.17
- IDE: VSCode
- Ollama: 0.1.28
```

### Description

I can successfully use Ollama locally.

I'd prefer to use a remote self-hosted Ollama instance. When adding an `apiBase` (e.g. `192.168.1.xxx:11434`), the continue extension no longer works; submitting the chat is frozen/hangs on the rainbow outline (indicating it's waiting on a response).

### To reproduce

1. Run a remote instance of Ollama. Verify Ollama is running with `curl 192.168.1.xxx:11434` (responds with `Ollama is running`)
2. Add `apiBase` value to `config.json` in the `ollama` model.
3. Submit a sample query/chat
4. Get no response and no error, form is frozen with "loading" animation.

### Log output

N/A

I opened the Developer Tools window in VSCode, but I did not get any output related to `continue`.

**Comment by sestinj** [comment]
@MattyRad Are you entering literally `192.168.1.xxx:11434`? It's important to keep URL scheme (http:// or https://).

Otherwise, if you could share the whole model object from your config, or any logs on the Continue side (cmd+shift+P, "Toggle Developer Tools") or the Ollama side, I can try to further debug. Many folks have used remote before so either there's some brand new regression or just a small blip in config (in which case we ought to improve the docs)
